class_name HomeScreen
extends Control
signal route_requested(route: String)

func setup(profile: Dictionary, _world: int) -> void:
	var safe := UiKit.screen_background(self,UiKit.SKY,"res://assets/art/airport_atmosphere.png")
	var column := VBoxContainer.new()
	column.add_theme_constant_override("separation",9)
	safe.add_child(column)
	var row := UiKit.header(tr("game.level")+" "+str(profile.get("current_level",1)),int(profile.get("coins",0)),false)
	var gear := UiKit.icon_button("settings")
	gear.pressed.connect(func() -> void: route_requested.emit("settings"))
	(row["root"] as HBoxContainer).add_child(gear)
	column.add_child(row["root"])
	var brand := PanelContainer.new()
	brand.add_theme_stylebox_override("panel",UiKit.panel(Color(1,.98,.92,.87),18))
	brand.add_child(UiKit.art("res://assets/art/logo.png",60))
	column.add_child(brand)
	var hero := AirportScene.new()
	hero.configure(profile,true)
	hero.zone_selected.connect(func(_zone: String) -> void: route_requested.emit("airport"))
	column.add_child(hero)
	var caption := UiKit.label(tr("home.hub_progress") % AirportEconomy.progress(profile.get("airport",{})),14,true)
	caption.add_theme_stylebox_override("normal",UiKit.panel(Color(1,.98,.92,.88),12))
	column.add_child(caption)
	var play := UiKit.button(tr("menu.continue"),UiKit.CORAL)
	play.pressed.connect(func() -> void: route_requested.emit("continue"))
	column.add_child(play)
	var daily := UiKit.button(tr("daily.today"),UiKit.GOLD,true)
	daily.pressed.connect(func() -> void: route_requested.emit("daily"))
	column.add_child(daily)
	column.add_child(UiKit.navigation("",func(id: String) -> void: route_requested.emit(id)))
